name: Deploy React Notes Crud
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t sergio7174/reactnotescrud-backend 
      - name: Publish Image to docker hub
        run: docker push sergio7174/reactnotescrud-backend
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull sergio7174/reactnotescrud-backend:latest
      - name: Delete old container
        run: docker rm -f reactnotescrud-backend-container 
      - name: Run Docker Container
        run: docker run -d -p 5555:5555 --name bookstoreactnotescrud-backend-container -e MONGO_PASSWORD='${{ secrets.MONGOdb_PASSWORD }}' sergio7174/reactNoteCrudAWSEC2_backend 